# Generated by Django 4.1.2 on 2023-05-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_teacher_alter_student_age_alter_student_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(unique=True),
        ),
    ]
