# Generated by Django 4.0.5 on 2022-06-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=20)),
                ('dlocation', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Dept',
            },
        ),
    ]
